[package]
name = "shooting-star"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
native-tls = "0.2.11"
tokio = { version = "1.36.0", features = ['full'] }
tokio-native-tls = "0.3.1"
url = "2.5.0"
